// Code generated by Feihan SDK Generator. DO NOT EDIT.

/** 设置正在输入中（请求） */
export interface CreateTypingReq {
  chat_id?: string; // 聊天 id
}

/** 设置正在输入中（响应） */
export interface CreateTypingResp {
}

/** 清除正在输入中（请求） */
export interface DeleteTypingReq {
  chat_id?: string; // 聊天 id
}

/** 清除正在输入中（响应） */
export interface DeleteTypingResp {
}
