// Code generated by Feihan SDK Generator. DO NOT EDIT.
import type { Int64 } from '@/core/types';

/** 发送消息（请求） */
export interface SendMessageReq {
  message_type?: string; // 消息类型
  message_content?: MessageContent; // 消息内容
  chat_id?: string; // 聊天 id
  reply_message_id?: string; // 本条消息回复的消息 id
}

/** 发送消息（响应） */
export interface SendMessageResp {
  message_id?: string; // 消息 id
}

/** 获取消息（请求） */
export interface GetMessageReq {
  message_id?: string; // 消息 id
}

/** 获取消息（响应） */
export interface GetMessageResp {
  message?: Message; // 消息
}

/** 撤回消息（请求） */
export interface RecallMessageReq {
  message_id?: string; // 消息 id
}

/** 撤回消息（响应） */
export interface RecallMessageResp {
}

/** 阅读消息（请求） */
export interface ReadMessageReq {
  message_id?: string; // 消息 id
}

/** 阅读消息（响应） */
export interface ReadMessageResp {
}

/** 消息内容 */
export interface MessageContent {
  text?: MessageText; // 文本消息
  image?: MessageImage; // 图片消息
  sticker?: MessageSticker; // 表情包消息
  video?: MessageVideo; // 视频消息
  audio?: MessageAudio; // 语音消息
  file?: MessageFile; // 文件消息
  user_card?: MessageUserCard; // 个人名片消息
  group_card?: MessageGroupCard; // 群名片消息
  group_announcement?: MessageGroupAnnouncement; // 群公告
  card?: MessageCard; // 卡片消息
}

/** 文本消息 */
export interface MessageText {
  content?: string; // 内容
  attachment_list?: MessageTextAttachment[]; // 附件列表，在 content 中的格式为 {{attach:id}}
  mention_user_list?: MessageTextMentionUser[]; // 被@人列表，在 content 中的格式为 {{mention:user_id}}，@所有人的 user_id 为 all
  emoji_list?: MessageTextEmoji[]; // Emoji 列表，在 content 中的格式为 {{emoji:emoji_id}}
}

/** 附件 */
export interface MessageTextAttachment {
  attachment_id?: string; // 附件 id，在 content 中引用，引用格式为 {{id}}，客户端自定义
  attachment_type?: string; // 附件类型
  attachment_content?: MessageTextAttachmentContent; // 附件内容
}

/** 附件内容 */
export interface MessageTextAttachmentContent {
  image?: FileImage; // 图片
}

/** 图片文件 */
export interface FileImage {
  image?: File; // 大图，宽高最大 1024
  image_width?: Int64; // 图片宽度
  image_height?: Int64; // 图片高度
  image_origin?: File; // 原图
  image_origin_width?: Int64; // 原图宽度
  image_origin_height?: Int64; // 原图高度
  image_thumb_bytes?: Uint8Array; // 缩略图数据，宽高最大 40
  image_thumb_mime?: string; // 缩略图文件类型
  image_dominant_color?: string; // 图片主色调，格式为 #ffffff
}

/** 文件 */
export interface File {
  file_id?: string; // 文件 id
  file_mime?: string; // 文件类型
  file_size?: Int64; // 文件大小
  file_encryption?: Encryption; // 文件加密
}

/** 加密项 */
export interface Encryption {
  encryption_algorithm?: string; // 加密算法
  encryption_key?: Uint8Array; // 加密密钥
  encrypted_size?: Int64; // 加密后的大小
}

/** @ 用户 */
export interface MessageTextMentionUser {
  user_id?: UserId; // 用户 id
  user_name?: string; // 当时的用户名称
  is_in_chat?: boolean; // 当时该用户是否在聊天中
}

/** 用户 id */
export interface UserId {
  user_id?: string; // 用户在飞函里的 id，同一个用户在所有应用中的 user_id 均相同
  union_user_id?: string; // 用户在同一应用组内的 id，同一个用户在相同应用组下的不同应用中的 union_user_id 均相同
  open_user_id?: string; // 用户在应用内的 id，同一个用户在不同应用中的 open_user_id 均不同
}

/** Emoji */
export interface MessageTextEmoji {
  emoji_id?: string; // Emoji id
  emoji_name?: string; // 当时的 Emoji 名称
}

/** 图片消息 */
export interface MessageImage {
  image?: FileImage; // 图片
}

/** 表情包消息 */
export interface MessageSticker {
  sticker?: Sticker; // 表情包
}

/** 表情包 */
export interface Sticker {
  sticker_id?: string; // 表情包 id
  sticker_name?: string; // 表情包名称
  sticker_name_i18n?: Record<string, string>; // 表情包名称国际化
  sticker_image?: FileImage; // 表情包图片
}

/** 视频消息 */
export interface MessageVideo {
  video?: FileVideo; // 视频
}

/** 视频文件 */
export interface FileVideo {
  video?: File; // 视频
  video_width?: Int64; // 视频宽度
  video_height?: Int64; // 视频高度
  video_duration?: number; // 视频时长
  video_preview?: FileImage; // 视频预览图
}

/** 语音消息 */
export interface MessageAudio {
  audio?: FileAudio; // 音频
}

/** 音频文件 */
export interface FileAudio {
  audio?: File; // 音频
  audio_duration?: number; // 音频时长
}

/** 文件消息 */
export interface MessageFile {
  file?: File; // 文件
  filename?: string; // 文件名
}

/** 个人名片消息 */
export interface MessageUserCard {
  user_id?: UserId; // 用户 id
}

/** 群名片消息 */
export interface MessageGroupCard {
  chat_id?: string; // 聊天 id
}

/** 群公告 */
export interface MessageGroupAnnouncement {
  message_text?: MessageText; // 公告内容
}

/** 卡片消息 */
export interface MessageCard {
  schema?: string; // 卡片版本
  v1?: MessageCardV1; // v1 版本
}

/** v1 版本 */
export interface MessageCardV1 {
  header?: MessageCardV1Header; // 卡片标题
  body?: MessageCardV1Body; // 卡片正文
  footer?: MessageCardV1Footer; // 卡片底部
}

/** 卡片标题 */
export interface MessageCardV1Header {
  title?: string; // 标题文本
  title_i18n?: Record<string, string>; // 标题文本国际化
  template?: string; // 标题颜色模板
}

/** 卡片正文 */
export interface MessageCardV1Body {
  message_text?: MessageText; // 卡片正文文本消息
  message_text_i18n?: Record<string, MessageText>; // 卡片正文文本消息国际化
}

/** 卡片底部 */
export interface MessageCardV1Footer {
  button_list?: MessageCardV1Button[]; // 按钮列表
  button_align?: string; // 按钮排版
}

/** 卡片按钮 */
export interface MessageCardV1Button {
  button_text?: string; // 按钮文本
  button_text_i18n?: Record<string, string>; // 按钮文本国际化
  template?: string; // 按钮样式模板，取值 default, primary, danger, primary_text, danger_text, primary_filled, danger_filled
  link?: MessageCardV1ButtonLink; // 按钮跳转链接
}

/** 跳转链接 */
export interface MessageCardV1ButtonLink {
  url?: string; // 默认链接地址
  android_url?: string; // 安卓链接地址
  ios_url?: string; // ios 链接地址
  pc_url?: string; // 桌面端链接地址
}

/** 消息 */
export interface Message {
  message_id?: string; // 消息 id
  message_type?: string; // 消息类型
  message_status?: string; // 消息状态
  message_content?: MessageContent; // 消息内容
  message_created_at?: Int64; // 消息创建时间（毫秒）
  chat_id?: string; // 聊天 id
  chat_seq_id?: Int64; // 服务端生成的聊天级别的消息趋势递增 id，用于单链排序
  sender_id?: UserId; // 发送者 id
  reply?: MessagePropReply; // 回复属性
}

/** 消息回复属性 */
export interface MessagePropReply {
  reply_message_id?: string; // 本条消息回复的消息 id
}

/** 接收消息 */
export interface EventMessageReceiveBody {
  message?: Message; // 消息
}
